### ISSUE TITLE
URL Error

### ISSUE THREAD

**Issue by parthparmar15** [eddiewebb/hugo-resume#16]
Hello,
I am getting the following error. It will be a great help if you can look into it.Thank you in advance.

Building sites … ERROR 2018/05/01 22:31:56 Error while rendering "taxonomyTerm" in "": template: /Resume/layouts/_default/terms.html:8:68: executing "Resume/layouts/_default/terms.html" at <absURL>: wrong number of args for absURL: want 1 got 0
ERROR 2018/05/01 22:31:56 Error while rendering "home" in "": template: /Resume/layouts/index.html:8:68: executing "/Resume/layouts/index.html" at <absURL>: wrong number of args for absURL: want 1 got 0

**Comment by eddiewebb** [comment]
Most likely you have not provided the required .Site.Params.profileImage url in your config file.
