### ISSUE TITLE
`-remove-` penetrates mailto.

### ISSUE THREAD

**Issue by momotaro98** [eddiewebb/hugo-resume#26]
Hi, @eddiewebb san.

I'm a fan of this theme. 

I found that, in [here](https://github.com/eddiewebb/hugo-resume/blob/c9325aa3dd394633fe5b2fb6598ef0f9f876405b/layouts/partials/about.html#L12) , `-remove-` penetrates mailto link.

Actually, [Your site](https://edwardawebb.com/) has 
OlliT-remove-ech@gmail.com .

**Comment by eddiewebb** [comment]
Yes, this is by design as a primitive spam harvesting defense.

Humans will see the right email on the page and fix it. 

If you'd like to explore other means to obfuscate the email from online bots I am open to such contributions.

**Comment by momotaro98** [comment]
I understand the intention. Thanks.
