### ISSUE TITLE
Error building site: failed to render pages: 

### ISSUE THREAD

**Issue by UTexas80** [eddiewebb/hugo-resume#30]
I love the site but I am getting an error in RStudio when I render the site using blogdown::serve_site()
The error I receive is 
"Error: Error building site: failed to render pages: render of "section" failed: "C:\Users\myname\Documents\GitHub\myname_hugoResume\themes\hugo-resume\layouts\_default\section.html:8:11": execute of template failed: template: _default\section.html:8:11: executing "main" at <partial (printf "%s%...>: error calling partial: Partial "postSummary" not found
The system cannot find the path specified.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\gfalk\AppData\Roaming\Hugo\hugo.exe" -b / -D -F -d "public" --themesDir themes -t hugo-resume' execution failed with error code 1"

I looked through the section.html but didn't see any issues.

Thank you for your time and consideration.

**Comment by firasm** [comment]
I get the same error, something looks broken. Unfortunately this was the first theme I tried on Hugo so can't troubleshoot much...

**Comment by lbejta** [comment]
Same here! I would love to use the theme, but I unfortunately can't. Any updates about the error?

**Comment by JulienRouse** [comment]
At line 8 in `themes\hugo-resume\layouts\_default\section.html` replace 

`{{ partial (printf "%s%s" .Section "postSummary") . }}`

by 

{{ partial (printf "%s%s" .Section "Summary") . }}

**Comment by MarvinKweyu** [comment]
I've read through Julien's answer:
> **Long version**
> The error message `"Error: Error building site: failed to render pages: render of "section" failed: "C:\Users\myname\Documents\GitHub\myname_hugoResume\themes\hugo-resume\layouts_default\section.html:8:11": execute of template failed: template: _default\section.html:8:11: executing "main" at <partial (printf "%s%...>: error calling partial: Partial "postSummary" not found` has multiple parts.

I'v got a similar problem only I do'nt understand it.
```bash

Building sites … WARN 2019/09/26 17:50:56 Page's .
Hugo is deprecated and will be removed in a future release. Use the global hugo function.
Total in 17 ms

Error: Error building site: failed to render pages: render of "home" failed: execute of 
template failed: template: index.html:2:6: executing "main" at <partial "about.html" .>: 
error calling partial: "/run/media/marvin/DriveEtCetera/ImMarvin/themes/hugo-resume/layouts/partials/about.html:12:77": 
execute of template failed: template: partials/about.html:12:77: 
executing "partials/about.html" at <substr .Site.Params.email 5>: error calling substr: start position out of bounds for 0-byte string

```
Can someone explain to me what is happening?

**Comment by dayuebai** [comment]
@MarvinKweyu I have the same issue. Can't figure it out.

**Comment by eddiewebb** [comment]
@MarvinKweyu i think that means you didnt provide an email in config, so about.html partial cant render.

@UTexas80 - the template uses "blog" not post. So if you want a posts folder instead, you would need to rename the related assets as @JulienRouse  points out above.

I will add the blog section to `exampleSite` to make this clear.

**Comment by procava** [comment]
I also get the following error. Is there any approach reach to the solution:

> blogdown::serve_site()
Building sites â€¦ ERROR 2020/07/07 09:31:49 unexpected data type [][]string in file AGENT.csv
ERROR 2020/07/07 09:31:49 unexpected data type [][]string in file GROUPS.csv
ERROR 2020/07/07 09:31:49 unexpected data type [][]string in file PROSUL_BASE_GROUPS.csv
ERROR 2020/07/07 09:31:49 unexpected data type [][]string in file PROSUL_BASE_WORKS.csv
Total in 444 ms
Error: Error building site: failed to render pages: write C:\Users\bapti\OneDrive - ACQUABUILD, LDA\PROCAVA@WEB\public\tags\ai\index.html: Incorrect function.
Building sites â€¦ ERROR 2020/07/07 09:31:49 unexpected data type [][]string in file AGENT.csv
ERROR 2020/07/07 09:31:49 unexpected data type [][]string in file GROUPS.csv
ERROR 2020/07/07 09:31:49 unexpected data type [][]string in file PROSUL_BASE_GROUPS.csv
ERROR 2020/07/07 09:31:49 unexpected data type [][]string in file PROSUL_BASE_WORKS.csv
Total in 570 ms
Error: Error building site: logged 4 error(s)
The system cannot find the path specified.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\bapti\AppData\Roaming\Hugo\hugo.exe" -b / -D -F -d "public" --themesDir themes -t educenter-hugo' execution failed with error code 1

**Comment by tusharsathe1** [comment]
I am still getting below error:

Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:2:6: executing "main" at <partial "about.html" .>: error calling partial: "C:\Hugo\my-site-2\themes\hugo-resume\layouts\partials\about.html:12:77": execute of template failed: template: partials/about.html:12:77: executing "partials/about.html" at <substr .Site.Params.email 5>: error calling substr: start position out of bounds for 0-byte string

I have my email address added to the config.toml file.
