### ISSUE TITLE
experience.json unable to format the text

### ISSUE THREAD

**Issue by wojciehm** [eddiewebb/hugo-resume#33]
Hi.

I am unable to format experience.json as needed.

I have a following text 

VMware: Installation of ESX/ESXi according to company standards
Automated VMware deployment according to company standards
Planning and configuration of networking and storage solutions
Performance analysis and fine-tuning parameters to improve throughput and effectively utilize system resources

After each line, there is a line break. How can I add break line <br/> after each section? I tried with \n but it is not working.

**Comment by eddiewebb** [comment]
I suspect this is just because HTML doesnt care about line breaks and I am not passing this field through any special rendering. You could try adding `<br />`, I probably wont markdownify this field until I complete #43  since that will change the format anyhow.
