### ISSUE TITLE
Main Page _index.md doesnt render

### ISSUE THREAD

**Issue by SeeSharpy** [eddiewebb/hugo-resume#49]
Running the latest version of Hugo on both my site and the example site in the theme, and the content on the home page doesn't get rendered.

Is there a command i need to run to get it to work?

**Comment by russellrosario** [comment]
Same issue, not sure how to fix

**Comment by timrobertsdev** [comment]
I'm experiencing this as well, hugo 0.64.0. content/_index.md exists and has valid content, but no rendered on the home page. exampleSite doesn't render properly either.

**Comment by timrobertsdev** [comment]
Found the fix, add this to your `config.toml`:
```
[markup.goldmark.renderer]
unsafe= true```

**Comment by russellrosario** [comment]
Works, thanks

This bug was only on localhost

**Comment by eddiewebb** [comment]
I have removed html from index, which should only contain valid markdown.
