### ISSUE TITLE
Better? template for index.json [search]

### ISSUE THREAD

**Issue by kaushalmodi** [eddiewebb/hugo-resume#6]
I tried this out and it works great! 

- No need to manually manage the commas
- Also it does not matter if the front-matter doesn't have `tags` or `categories` or both!

```
{{- $.Scratch.Add "index" slice -}}
{{- range .Site.RegularPages -}}
    {{- $.Scratch.Add "index" (dict "title" .Title "tags" .Params.tags "categories" .Params.categories "contents" .Plain "permalink" .Permalink) -}}
{{- end -}}
{{- $.Scratch.Get "index" | jsonify -}}
```

[Ref][1]

[1]: https://discourse.gohugo.io/t/creating-json-with-hugo-how-to-escape-slashes/8461/3?u=kaushalmodi

**Comment by eddiewebb** [comment]
That's great! Thanks

**Comment by eddiewebb** [comment]
implemented in gist and theme
