### ISSUE TITLE
blog posts and projects info is not displayed on homepage

### ISSUE THREAD

**Issue by py563** [eddiewebb/hugo-resume#61]
I was updating my website and found this issue, will cross check if it happening only on my system because I have same settings in ```config.toml``` as @eddiewebb website.

In the meantime please let me know if that is the case with others too on the latest commit.

**Comment by hodsonus** [comment]
@py563 I seem to be having the same problem, did you ever reach a resolution? @eddiewebb

**Comment by py563** [comment]
I am not sure why I closed this, I am still facing issue
