### ISSUE TITLE
use "range where" to search for category products

### ISSUE THREAD

**Issue by vistad** [eddiewebb/hugo-resume#65]
The described model searches across the whole site - but this is not what I want. How I can implement search in one category following your model? 

In Content folder on my Hugo website I have created folders Women, Men etc. holding product-descriptions.md A woman who is looking for a women shoes, initiates her search on some women page - but Fuse.js searches all content folders and returns results for Women, Men, Kids etc.

I am trying to use:
{{- range where .Pages “categories” “women” $name, $items := .Site.Taxonomies.products }}

but I get the error message:
undefined variable "$name"

How I can use "range where" to search for category products?
My case is described here: https://discourse.gohugo.io/t/range-where-error-message/26418
Thank you!

**Comment by eddiewebb** [comment]
Sorry I can't help customizations.
