### ISSUE TITLE
Mention jquery inclusion in the `footerfiles` block? [search gist]

### ISSUE THREAD

**Issue by kaushalmodi** [eddiewebb/hugo-resume#8]
Hello,

This might have been obvious to many, but as I don't know JS at all, it had to spend some time to later realize that I needed to add the below to the footerfiles block:

```html
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
```

.. because I didn't already have jquery loaded for my site.

Can you make a small mention of this step on the gist?

*Hope using these issues is fine, because I the gist comments don't send notifications.*

---

PS: I have mentioned your gist on the Hugo Discourse forum: https://discourse.gohugo.io/t/site-search-implemented-using-just-hugo-js-no-gulp-grunt-etc/10947

**Comment by eddiewebb** [comment]
Added to gist, thank you!
