### ISSUE TITLE
JQuery Slim breaks JQuery Easing

### ISSUE THREAD

**Issue by awhitford** [eddiewebb/hugo-resume#80]
https://github.com/eddiewebb/hugo-resume/blob/cd8970ab61c579215f78f50319aea8493627db94/layouts/_default/baseof.html#L48

Unfortunately, I noticed that PR #72 unintentionally breaks the JQuery Easing plugin, with
> Uncaught TypeError: Cannot read property 'swing' of undefined

Despite Bootstrap 4 being happy with JQuery Slim, JQuery Easing requires the _Normal_ edition.

**Comment by awhitford** [comment]
PR #84 will resolve this issue.

**Comment by eddiewebb** [comment]
thank you @awhitford
