### ISSUE TITLE
Adding tables

### ISSUE THREAD

**Issue by oldi** [eddiewebb/hugo-resume#88]
First of all, many thanks for this great hugo theme!I really enjoy it! 💯 points!

I would love to add markup tables with line pattern and potentially adjustable using CSS.

A nice theme I want to use for my blog is cupper
https://themes.gohugo.io/cupper-hugo-theme/

Do you have any hints on how to add tables to your theme?

Sorry, but I am not a programmer but ecologist :)

EDIT: just to give my request more content: I would love to present my publications and projects in a table (there are plenty of publications) and it would be tedious to have them explained in depth like the way it is done now.

**Comment by eddiewebb** [comment]
Markdown tables are supported.


```
| heading | heading |
|-----------|--------|
| Cell | cell |
```

| heading | heading |
|-----------|--------|
| Cell | cell |
