### ISSUE TITLE
How to conditionally output Tags: in the search template? [search]

### ISSUE THREAD

**Issue by kaushalmodi** [eddiewebb/hugo-resume#9]
Hello,

Hopefully this is a last question related to search.. *for today*.

This is more of a JS question.. I have:

```html
<script id="search-result-template" type="text/x-js-template">
    <div id="summary-${key}">
        <h4><a href="${link}">${title}</a></h4>
        <p>${snippet}</p>
        <small>
            <table>
                <tr><td>Tags</td><td>${tags}</td></tr>
                <tr><td>Categories</td><td>${categories}</td></tr>
            </table>
        </small>
    </div>
</script>
```

How can I prevent printing `<tr><td>Tags</td><td>${tags}</td></tr>` if `${tags}` is `null`? 

Just to try my luck, I tried:

```
                if (${tags}!=null) {
                    <tr><td>Tags</td><td>${tags}</td></tr>
                }
```

but of course that didn't work..

**Comment by eddiewebb** [comment]
Added some rather 'dumb' logic to the trivial find and replace.  

You wrap a line in `${ isset <key-name>}Text to show${ end }` and it will only show contents if the key if populated in the payload.  It won't support multiline wrapping based on the regexp used though.

**Comment by kaushalmodi** [comment]
Works great! Thanks!
