### ISSUE TITLE
Can't see project and publications section

### ISSUE THREAD

**Issue by shusingh** [eddiewebb/hugo-resume#91]
Other sections are visible, but I can not see the projects and publications section. I have set the value to true in the config file. What could be the reason for it?
This code should load it on the webpage, but it doesn't:
{{ if .Site.Params.showProjects }}
      {{ with .Site.GetPage "section" "projects/creations" }}
         {{ .Scratch.Set "sectionId" "projects" }}
         {{ partial "sectionSummary" . }}
      {{ end }}
   {{ end }}

**All the sections with simple code like this are visible, :**
{{ if .Site.Params.showEducation }}
       {{ partial "portfolio/education.html" . }}
   {{ end }}

**but sections having code like this are not:**
{{ if .Site.Params.showProjects }}
      {{ with .Site.GetPage "section" "projects/creations" }}
         {{ .Scratch.Set "sectionId" "projects" }}
         {{ partial "sectionSummary" . }}
      {{ end }}
   {{ end }}

What should I do?

**Comment by py563** [comment]
can you show your folder structure?
